### ISSUE TITLE
Use waitEvent

### ISSUE THREAD

**Issue by cc-jj** [Squirrelbear/Wordle-CPP-SMFL#1]
The main game loop uses [pollEvent](https://github.com/Squirrelbear/Wordle-CPP-SMFL/blob/1fd0b6eab3b8ecb5c7cf8e9d86cdabb1dc96ccb0/WordleSFML/WordleSFML/SFMLGame.cpp#L21) which causes unnecessary renders if no events are received.

It seems the intention is to sleep between events, which can be achieved with [waitEvent](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Window.php#aaf02ab64fbc1d374eef3696df54137bc).

**Comment by Squirrelbear** [comment]
I have pushed a new version that uses waitEvent instead. Thank you for the suggestion.

https://github.com/Squirrelbear/Wordle-CPP-SMFL/commit/f91db1204959a58c9043261e2283be1d6ad6b560
